/**
 * @author Hugo Ramirez Jr.
 * @date 12/12/2025
 * Module 2 - Read and Write Data Files
 * @description This class reads data from the file generated by Main.java
 */
package com.example;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class ReadDataFile {

    public static void main(String[] args) {
        try {
            File file = new File("Hugo_datafile.dat");
            Scanner scanner = new Scanner(file);

            System.out.println("Reading data from file:\n");

            while (scanner.hasNextLine()) {
                System.out.println(scanner.nextLine());
            }

            scanner.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found.");
            e.printStackTrace();
        }
    }
}